---
services:
  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    environment:
      - PUID=0
      - PGID=0
      - TZ=America/Los_Angeles
    volumes:
      - /home/docker/radarr/config:/config 
      - /Volume1:/data
    networks:
      - sabnzbd_default
    ports:
      - 7878:7878
    restart: unless-stopped
  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    environment:
      - PUID=0
      - PGID=0
      - TZ=America/Los_Angeles
    volumes:
      - /home/docker/sonarr/data:/config
      - /Volume1:/data
    networks:
      - sabnzbd_default
    ports:
      - 8989:8989
    restart: unless-stopped
  sabnzbd:
    image: lscr.io/linuxserver/sabnzbd:latest
    container_name: sabnzbd
    environment:
      - PUID=0
      - PGID=0
      - TZ=America/Los_Angeles
    volumes:
      - /home/docker/sabnzbd:/config
      - /Volume1/usenet:/data/usenet
    networks:
      - sabnzbd_default
    ports:
      - 8080:8080 
    restart: unless-stopped
  plex:
    image: lscr.io/linuxserver/plex:latest
    container_name: plex
    privileged: true
    devices:
      - /dev/dri:/dev/dri
    environment:
      - PUID=0
      - PGID=0
      - VERSION=docker
      - TZ=America/Los_Angeles
      - PLEX_CLAIM=claim-qyNgQ1rgzezMuUkau6Nn
    volumes:
      - /home/docker/plex/config:/config
      - /share/plex/transcode:/transcode
      - /Volume1/Media:/data
    ports:
      - 32400:32400
    restart: unless-stopped

networks:
  sabnzbd_default:
    name: sabnzbd_default
